# Generated by Django 3.2.12 on 2022-02-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('material', models.CharField(max_length=30)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
