# Generated by Django 3.2.12 on 2022-02-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('SS 202', 'SS 202'), ('SS 304', 'SS 304'), ('MS + PVC', 'MS +PVC'), ('SS + PVC', 'SS +PVC')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Plate Racks', 'Plate Racks'), ('Horizontal Plate Racks(Single)', 'Horizontal Plate Racks(Single)'), ('Horizontal Plate Racks(Single)', 'Horizontal Plate Racks(Double'), ('Quarter Plate Racks(Double)', 'Quarter Plate Racks(Double)'), ('Quarter Plate Racks(Four Section)', 'Quarter Plate Racks(Four Section)'), ('Soup Bowl(Horizontal)', 'Soup Bowl(Horizontal)'), ('Soup Bowl(Vertical)', 'Soup Bowl(Vertical)'), ('Soup Bowl Racks (W/ Plate)', 'Soup Bowl Racks (W/ Plate)'), ('Katori Racks', 'Katori Racks'), ('Plizner Glass Racks', 'Plizner Glass Racks'), ('Wine Glass Racks', 'Wine Glass Racks'), ('Coffee Mug/Kulud Racks', 'COffee Mug/Kulud Racks'), ('Onion Potato Trolley', 'Onion Potato Trolley'), ('Onion Potato Trolley (W/ Partition)', 'Onion Potato Trolley (W/ Partition)'), ('Wine Holder', 'Wine Holder')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('7.5 inch', '7.5 inch'), ('8 inch', '8 inch'), ('9 inch', '9 inch'), ('10 inch', '10 inch'), ('11 inch', '11 inch'), ('12 inch', '12 inch'), ('13 inch', '13 inch'), ('14 inch', '14 inch'), ('24 x 24 x 30', '24 x 24 x 30')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
